---
name: vscode
description: "VSCode configuration for MCP server integration"
config_type: ide
enabled: true
server_name: "mide"
config_paths:
  linux: "~/.config/Code/User/mcp_settings.json"
  darwin: "~/Library/Application Support/Code/User/mcp_settings.json"
  win32: "%APPDATA%/Code/User/mcp_settings.json"
compatibility:
  cursor: false
  vscode: true
  claude: false
  openai: false
tags: ["ide", "vscode", "mcp"]
status: active
---
