---
name: global_settings
description: "Global configuration settings for Mide"
config_type: global
setup:
  auto_configure_ides: true
  auto_sync_configs: true
  backup_before_deploy: true
ide:
  auto_configure: true
  default_server_name: "mide"
global:
  mcp:
    servers:
      mide:
        entry_point: "./dist/integrations/mcp/index.js"
compatibility:
  cursor: true
  vscode: true
  claude: true
  openai: true
tags: ["global", "settings", "defaults"]
status: active
---
