---
name: cursor
description: "Cursor IDE configuration for MCP server integration"
config_type: ide
enabled: true
server_name: "mide"
config_paths:
  linux: "~/.cursor/mcp.json"
  darwin: "~/Library/Application Support/Cursor/mcp.json"
  win32: "%APPDATA%/Cursor/mcp.json"
compatibility:
  cursor: true
  vscode: false
  claude: false
  openai: false
tags: ["ide", "cursor", "mcp"]
status: active
---
