---
name: openai
description: "OpenAI API configuration for MCP server integration"
config_type: ide
enabled: true
config_type_api: "mcp_agent"
config_file: "./openai-mcp-config.yaml"
server_name: "mide"
api_key_env: "OPENAI_API_KEY"
compatibility:
  cursor: false
  vscode: false
  claude: false
  openai: true
tags: ["ide", "openai", "mcp", "api"]
status: active
---
