---
name: mcp_servers
description: "MCP server configuration definitions"
config_type: mcp
servers:
  mide:
    name: "mide"
    description: "Mide MCP server for intelligent development environment"
    entry_point: "./dist/integrations/mcp/index.js"
    command: "node"
    args: ["{{entry_point}}"]
    env:
      PROJECT_ROOT: "{{project_root}}"
    version: "3.1.0"
    status: "active"
compatibility:
  cursor: true
  vscode: true
  claude: true
  openai: true
tags: ["mcp", "servers", "core"]
status: active
---
